//1. Login API
export const LOGIN_CHECK = "LOGINCHECK";
export const LOGIN_ERROR = "LOGINERROR";
export const LOGIN_SUCCESS = "LOGINESUCCESS";

//2. Register
export const CHECK_EMAIL = "CHECKEMAIL";
export const MAIL_ERROR = "MAIL_ERROR";
export const MAIL_SUCCESS = "MAIL_SUCCESS";

// logout
export const LOGOUT_CHECK = "LOGOUT_CHECK";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const USER_REGISTRATION_CHECK ="USER_REGISTRATION_CHECK";
export const USER_REGISTRATION_SUCCESS ="USER_REGISTRATION_SUCCESS";
export const USER_REGISTRATION_ERROR ="USER_REGISTRATION_ERROR";

//2.1 forgot password
export const FORGOT_PASSWORD_CHECK ="FORGOT_PASSWORD_CHECK";
export const FORGOT_PASSWORD_SUCCESS ="FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL ="FORGOT_PASSWORD_FAIL";


//3. Events Add (save)
export const EVENT_SAVE_CHECK ="EVENT_SAVE_CHECK";
export const EVENT_SAVE_SUCCESS ="EVENT_SAVE_SUCCESS";
export const EVENT_SAVE_FAIL ="EVENT_SAVE_FAIL";

    //3.1 Latest Event list
    export const LATESTEVENT_LIST_CHECK ="LATESTEVENT_LIST_CHECK";   
    export const LATESTEVENT_LIST_SUCCESS ="LATESTEVENT_LIST_SUCCESS";
    export const LATESTEVENT_LIST_FAIL ="LATESTEVENT_LIST_FAIL";

    //3.2 Event list
    export const EVENT_LIST_CHECK ="EVENT_LIST_CHECK";   
    export const EVENT_LIST_SUCCESS ="EVENT_LIST_SUCCESS";
    export const EVENT_LIST_FAIL ="EVENT_LIST_FAIL";

    //3.3 Event show
    export const EVENT_SHOW_CHECK ="EVENT_SHOW_CHECK";
    export const EVENT_SHOW_SUCCESS ="EVENT_SHOW_SUCCESS";
    export const EVENT_SHOW_FAIL ="EVENT_SHOW_FAIL";

    //3.3 Event Detail
    export const EVENT_DETAIL_CHECK ="EVENT_DETAIL_CHECK";
    export const EVENT_DETAIL_SUCCESS ="EVENT_DETAIL_SUCCESS";
    export const EVENT_DETAIL_FAIL ="EVENT_DETAIL_FAIL";

    // update event
export const UPDATEEVENT_SAVE_CHECK ="UPDATEEVENT_SAVE_CHECK";
export const UPDATEEVENT_SAVE_SUCCESS ="UPDATEEVENT_SAVE_SUCCESS";
export const UPDATEEVENT_SAVE_FAIL ="UPDATEEVENT_SAVE_FAIL";

    //3.4 Event edit
export const EVENT_EDIT_SUCCESS ="EVENT_EDIT_SUCCESS";
export const EVENT_EDIT_FAIL ="EVENT_EDIT_FAIL";

    //3.5 Delete Event
export const EVENT_DELETE_CHECK ="EVENT_DELETE_SUCCESS";
export const EVENT_DELETE_SUCCESS ="EVENT_DELETE_SUCCESS";
export const EVENT_DELETE_FAIL ="EVENT_DELETE_FAIL";
export const CLEAR_MSG ="CLEAR_MSG";
    //3.6 Delete Event
export const EVENT_UPDATE_SUCCESS ="EVENT_UPDATE_SUCCESS";
export const EVENT_UPDATE_FAIL ="EVENT_UPDATE_FAIL";

//4. Event Form Setup

export const EVENT_FORM_ADD_FIELD_SUCCESS ="EVENT_FORM_ADD_FIELD_SUCCESS";
export const EVENT_FORM_ADD_FIELD_FAIL ="EVENT_FORM_ADD_FIELD_FAIL";
export const HIDE_MODAL ="HIDE_MODAL";
export const ADD_MAIN_FORM ="ADD_MAIN_FORM";

// Entry List

export const ENTRY_LIST_CHECK ="ENTRY_LIST_CHECK";   
export const ENTRY_LIST_SUCCESS ="ENTRY_LIST_SUCCESS";
export const ENTRY_LIST_FAIL ="ENTRY_LIST_FAIL";
    
// Entry List

export const MODAL_LIST_CHECK ="MODAL_LIST_CHECK";   
export const MODAL_LIST_SUCCESS ="MODAL_LIST_SUCCESS";
export const MODAL_LIST_FAIL ="MODAL_LIST_FAIL";

// Entrant List

export const ENTRANT_LIST_CHECK ="ENTRANT_LIST_CHECK";   
export const ENTRANT_LIST_SUCCESS ="ENTRANT_LIST_SUCCESS";
export const ENTRANT_LIST_FAIL ="ENTRANT_LIST_FAIL";

//5 Profile
    // 5.1 profile data show
    export const PROFILE_SHOW_CHECK ="PROFILE_SHOW_CHECK";
    export const PROFILE_SHOW_SUCCESS ="PROFILE_SHOW_SUCCESS";
    export const PROFILE_SHOW_FAIL ="PROFILE_SHOW_FAIL";
    // 5.1 profile data Update
    export const UPDATEPROFILE_SAVE_CHECK ="UPDATEPROFILE_SAVE_CHECK";
    export const UPDATEPROFILE_SAVE_SUCCESS ="UPDATEPROFILE_SAVE_SUCCESS";
    export const UPDATEPROFILE_SAVE_FAIL ="UPDATEPROFILE_SAVE_FAIL";



